server:
  port: 8080

database:
  driver: sqlite
  dsn: ../memoryflow-data/data/memoryflow.db

storage:
  upload_dir: ../memoryflow-data/uploads



model:
  base_url: "https://xxx/v1"
  api_key: "你本地的key"
  model_name: "xxx"